# Generated by Django 4.2.9 on 2024-11-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(null=True)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.resourcebase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data Cite",
                "ordering": ("created_at",),
            },
        ),
    ]
