# Generated by Django 4.2.9 on 2024-11-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
        ("geonode_datacite", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datacite",
            options={"verbose_name_plural": "Data Cite"},
        ),
        migrations.RenameField(
            model_name="datacite",
            old_name="comment",
            new_name="detail",
        ),
        migrations.AlterField(
            model_name="datacite",
            name="resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.resourcebase",
            ),
        ),
    ]
