# Generated by Django 4.2.9 on 2024-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_datacite", "0003_remove_datacite_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacite",
            name="state",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Registered", "Registered"),
                    ("Findable", "Findable"),
                ],
                default="Draft",
                max_length=50,
            ),
        ),
    ]
